### ISSUE TITLE
Page not displaying correctly in Edge

### ISSUE THREAD

**Issue by SteveALee** [LeaVerou/markapp#29]
The interesting bits are missing :)

![screenshot 12](https://cloud.githubusercontent.com/assets/618922/18270660/ff44c5ba-7425-11e6-84ec-b9d5d7c810f8.png)

**Comment by LeaVerou** [comment]
Is there any JS error if you bring up the console?

/cc @gregwhitworth @patrickkettner

**Comment by patrickkettner** [comment]
So this is a bit interesting

There are no js errors, but what is happening is that our `HTMLTemplateElement` parser is being too strict compared to other browsers.

[you have a bit](https://github.com/LeaVerou/markapp/blob/da3b30c0918f836cddb75b805462a6c5ed8d6cbb/index.html). It creates two anchor tags, one before the content and one after the content. Not sure what the intention was, but I doubt it was this.

Regardless, this is breaking the parsing of the template element, and as a result, giving essentially an empty string over to mustache. Sadly, even after you remove the anchor tag it still breaks our parser :[ that is a bug on our end, and is being tracked internally to be fixed.

But! I have a workaround of sorts.

Technically, the "[correct](https://media.giphy.com/media/Fjr6v88OPk7U4/giphy.gif)" way of using template tag is rather than this

``` js
const templateData = document.querySelector('template').innerHTML
```

you do this

``` js
let templateNode = document.querySelector('template').content.cloneNode(true);
```

And since we are wanting to get the template as a string, we need to do the follow as well

``` js
const div = document.createElement('div')
div.appendChild(templateNode)

const templateData = div.innerHTML;
```

Since we cloned the template node, it is now a `HTMLDocumentFragment` rather than a `HTMLTemplateElement`, and the same parsing nonsense isnt there any longer. We just loose innerHTML as it fragments lack that extension. So we append the fragment to a div (or any non `<template>` element), and then `innerHTML`  _that_

super ugly and lame, _but_ it gets you working everywhere today

**Comment by SteveALee** [comment]
Fascinating explanation!

> "that is a bug on our end" 

 Who is that? Edge team?

**Comment by gregwhitworth** [comment]
Yes @patrickkettner mind making that bug public?

**Comment by gregwhitworth** [comment]
Nevermind, I made the bug public: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8664784/

**Comment by LeaVerou** [comment]
> Who is that? Edge team?

Yup, both Greg and Patrick are on the Edge team, hence why I CCed them :)

**Comment by LeaVerou** [comment]
Thanks for looking into it Patrick!

However, I thought the whole point of the `<template>` tag is that incomplete HTML is inert and is not fully parsed. If I have to append to the DOM to properly get its `innerHTML`, why not use any other element in the first place?

**Comment by patrickkettner** [comment]
you aren't appending it the the DOM. Normally would you just grab the `.content` and be on your way. Because of a bug in Edge, that is not a reliable source of that content. So you area creating an element in memory, moving the element over another inmemory element to get the `innerHTML` (again, because our template content isn't reliable).

**Comment by LeaVerou** [comment]
Ah, right, I read your response a bit too fast :)
Still, quite an ugly workaround. Anyhow, I'd merge a PR that fixes this.

**Comment by patrickkettner** [comment]
yeah, super gross. As mentioned before, it _will_ be fixed in Edge. Just a matter of when.

> Anyhow, I'd merge a PR that fixes this.

incoming...
